capitals = {'Alabama': 'Montgomery',
            'Alaska': 'Juneau',
            'Arizona': 'Phoenix',
            'Arkansas': 'Little Rock',
            'California': 'Sacramento',
            'Colorado': 'Denver',
            'Connecticut': 'Hartford',
            'Delaware': 'Dover',
            'Florida': 'Tallahassee',
            'Georgia': 'Atlanta',
            'Hawaii': 'Honolulu',
            'Idaho': 'Boise',
            'Illinois': 'Springfield',
            'Indiana': 'Indianapolis',
            'Iowa': 'Des Moines',
            'Kansas': 'Topeka',
            'Kentucky': 'Frankfort',
            'Louisiana': 'Baton Rouge',
            'Maine': 'Augusta',
            'Maryland': 'Annapolis',
            'Massachusetts': 'Boston',
            'Michigan': 'Lansing',
            'Minnesota': 'Saint Paul',
            'Mississippi': 'Jackson',
            'Missouri': 'Jefferson City',
            'Montana': 'Helena',
            'Nebraska': 'Lincoln',
            'Nevada': 'Carson City',
            'New Hampshire': 'Concord',
            'New Jersey': 'Trenton',
            'NewMexico': 'Santa Fe',
            'New York': 'Albany',
            'North Carolina': 'Raleigh',
            'North Dakota': 'Bismarck',
            'Ohio': 'Columbus',
            'Oklahoma': 'Oklahoma City',
            'Oregon': 'Salem',
            'Pennsylvania': 'Harrisburg',
            'Rhode Island': 'Providence',
            'South Carolina': 'Columbia',
            'South Dakota': 'Pierre',
            'Tennessee': 'Nashville',
            'Texas': 'Austin',
            'Utah': 'Salt Lake City',
            'Vermont': 'Montpelier',
            'Virginia': 'Richmond',
            'Washington': 'Olympia',
            'West Virginia': 'Charleston',
            'Wisconsin': 'Madison',
            'Wyoming': 'Cheyenne'
            }

english = { 'abbreviation': 'skrót, skrócenie',
            'acquisition': 'nabycie, przejęcie',
            'ambuguity': 'dwuznaczność, niejednoznaczność',
            'arbitrary': 'przypadkowy, dowolny',
            'biased': 'stronniczy, tendencyjny',
            'constrain': 'ograniczać',
            'constraint': 'ograniczenie, przymus',
            'contiguous': 'graniczący, sąsiadujący',
            'convinient': 'wygodny, praktyczny',
            'courage': 'męstwo, odwaga',
            'credentials': 'kwalifikacje, referencje',
            'derived': 'pochodny, pochodzący',
            'discourage': 'zniechęcać, zrażać',
            'distinct': 'odmienny, odróżniający się, unikalny',
            'doubt': 'wątpić, wątpliwość',
            'dump': 'wyrzucać, pozbywać się',
            'either': 'zarówno, albo',
            'emphasis': 'nacisk, szczególna uwaga',
            'enterprise': 'przedsiębiorstwo',
            'hassle': 'kłopot, zawracanie głowy',
            'heap': 'stos, sterta',
            'hint': 'wskazówka, podpowiedź',
            'horizontal': 'poziomy',
            'incorporate': 'zawierać',
            'layout': 'układ, plan',
            'literal': 'dosłowny, literalny',
            'merit': 'zasługa',
            'mitigate': 'zmniejszyć, złagodzić',
            'parse': 'rozbiór, analiza',
            'pickling': 'kiszenie',
            'pivot': 'obracać się',
            'redundand': 'zbędny',
            'relevant': 'istotny, trafny',
            'reliable': 'godny zaufania, niezawodny',
            'revenue': 'przychód, dochód',
            'rewind': 'przewijać do tyłu, cofać',
            'routine': 'ustalony porządek, rutyna',
            'self-sufficient': 'samowystarczalny, niezależny',
            'shallow': 'płytki',
            'significant': 'znaczący',
            'tangible': 'namacalny, zauważalny',
            'tedious': 'monotonny, żmudny',
            'ternary': 'potrójny',
            'tie': 'remis',
            'traversed': 'przecięty',
            'upon': 'od, na',
            'vertex': 'wierzchołek, szczyt',
            'vertical': 'pionowy',
            'wrap': 'zawijać, owijać'
            }